"""new fields in user model

Revision ID: 94510639eb3d
Revises: 39e93eee0f25
Create Date: 2020-10-28 17:13:33.763517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94510639eb3d'
down_revision = '39e93eee0f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
